//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\testreport")]
        public string ReportFolder {
            get {
                return ((string)(this["ReportFolder"]));
            }
            set {
                this["ReportFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("k/WeWpYKPGrYP7sUBqCReRvasRCvhIGvZJOdRj+aZmBB2+WxnC8bO77pyvDKCEEQQKzpH7Y0wDfVB056h" +
            "H32lQ6T9+DJqwXtKPWsN8Abz8WJw6kVLdSYalSo9FqgEn1El76Rwa9lWCs1p2P949VWrv14gvo9WtE2i" +
            "mMz5nK/GQk=")]
        public string AttendanceConnectionString {
            get {
                return ((string)(this["AttendanceConnectionString"]));
            }
            set {
                this["AttendanceConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.0.17,1433|AttendanceUser|jplefgsahuutsqwcmnhajreliqpsaltddweoiplnalsxz")]
        public string CnStr {
            get {
                return ((string)(this["CnStr"]));
            }
            set {
                this["CnStr"] = value;
            }
        }
    }
}
